// Password Generator Code
// This shows all possible outcomes of the password.

let upperCase = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"];
let lowerCase = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"];
let number = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"];
let SpecChar = ["!", "~", "@", "#", "*", "%", "^", "&", "$", "(", ")", "?", "+", "<", ">", "_", "{", "}", "[", "]", ","];

// This is what message prompts when you click "Generate Password" on the page.
function passwordRange() {
  let passwordTxt = window.prompt("Please input a numerical digit between 8 and 128 characters.");
  console.log(PasswordTxt);

  if (passwordTxt >= 8 && passwordTxt <= 128) {
    return passwordTxt;
  } else {
    alert("Please input a numerical digit between 8 and 128 characters.");
    return passwordRange();
  }
}
let generatePassword = function () {

  // Length of password is a minimum of 8 characters or more
  let input = passwordRange();

  // Questions prompted to user after hitting "confirm"
  let speccharConfirm = concat("Would you like your password to contain special characters?");
  let uppercaseConfirm = concat("Would you like your password to contain uppercase letters?");
  let lowercaseConfirm = concat("Would you like your password to contain lowercase letters?");
  let numberConfirm = concat("Would you like your password to contain numbers?");
  let confirms = [];

  // if statements prompt user to confirm what will be generated in their randomized password
  if (upperYes == true) {
    let addUpper = confirms.concat(upperCase);
    confirms = addUpper

  } else { }
  if (lowerYes == true) {
    let addLower = confirms.concat(lowerCase);
    confirms = addLower

  } else { }
  if (numYes == true) {
    let addNum = confirms.concat(number);
    confirms = addNum

  } else { }
  if (symYes == true) {
    let addSpec = confirms.concat(symbol);
    confirms = addSym

  } else { }
  if (upperYes == false && lowerYes == false && numYes == false && specYes == false) {
    alert("Select one of the following");
    return generatePassword();
  }
  // log to show confirms array filled with new variables
  console.log(confirms);

  let output = "";
  // Loop generated to create user password
  for (i = 0; i < input; i++) {
    output += confirms[Math.floor(Math.random() * confirms.length)];
    // allows user to see output of the randomized password generated by the prompts
    console.log(output);
  }
  // return password
  return output;

};

const generateBtn = document.querySelector("#generate");

// Write password to the #password input
function writePassword() {
  let password = generatePassword();
  let passwordText = document.querySelector("#password");

  passwordText.value = password;

}
// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);
